### ISSUE TITLE
Reproduction Parameters

### ISSUE THREAD

**Issue by jangsa** [ryoo-nakamura/OFDB#1]
Hi, I'm trying to reproduce the result of the original paper with imagenet-1k.

Could you kindly provide the parameters of 2D-OFDB-1k and 3D-OFDB-1k cases, especially "random pattern augmentation" and "random texture augmentation" if needed?
(I believe your methods "w/Aug." include above augmentations. I'll appreciate your advice if incorrect.)

Plus do you have any idea of how to solve "omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model.optim.model_or_params"?

Log is:
> Error executing job with overrides: ['data=grayimagefolder', 'data.baseinfo.name=2d-ofdb-1k', 'data.baseinfo.train_imgs=1000', 'data.baseinfo.num_classes=1000', 'data.trainset.root=/home/work/OFDB/dataset/2d-ofdb-1000', 'data.loader.batch_size=256', 'data.transform.no_aug=False', 'data.transform.auto_augment=rand-m9-mstd0.5-inc1', 'data.transform.re_prob=0.5', 'data.transform.color_jitter=0.4', 'data.transform.hflip=0.5', 'data.transform.vflip=0.5', 'data.transform.scale=[0.08,1.0]', 'data.transform.ratio=[0.75,1.3333]', 'data.mixup.prob=1.0', 'data.mixup.mixup_alpha=0.8', 'data.mixup.cutmix_alpha=1.0', 'data.mixup.switch_prob=0.5', 'model=vit', 'model.arch.model_name=vit_tiny_patch16_224', 'model.optim.learning_rate=0.001', 'model.scheduler.args.warmup_epochs=5', 'logger.group=cpmpare_instance_augmentation', 'mode=pretrain', 'output_dir=../models/ofdb_tiny_patch16_224/']
Traceback (most recent call last):
  File "/home/work/OFDB/main.py", line 195, in main
    optimizer = instantiate(cfg.model.optim, model=model)
  File "/home/.pyenv/versions/anaconda3-2023.03/envs/hyb/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/.pyenv/versions/anaconda3-2023.03/envs/hyb/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 340, in instantiate_node
    value = node[key]
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model.optim.model_or_params
    full_key: model.optim.model_or_params
    object_type=dict

I added "model_or_params: ???" to yaml files and inserted following:
> cfg.model.optim.model_or_params = model

just before "optimizer = instantiate(cfg.model.optim, model=model)" in main.py, but assigning premitive values seem not accepted.

Please be advised that I came across several conflicts and obsolete dependency problems with the requirements.txt.
So I've switched several packages.
Their versions are:
> timm 0.9.16
pytorch-metric-learning  1.3.2
torch  2.0.1
torchaudio  .0.2+cu118
torchvision   0.15.2

Sorry if there's something weird in above.
I'll greatly appreciate your advice!

**Comment by ryoo-nakamura** [comment]
Hi @jangsa ,thank you for interesting my paper.
I have saved the pre-trained model with ramdom patch patern and random texture data augmentation you asked for at the following [link](https://drive.google.com/drive/u/1/folders/1GUlRQwRPw0qx56L1Voez6RulYXGLgmuw) .
(However, the 2d-ofdb-1k patch aug. and the pre-trained models for texture and path aug. have been turned in by a co-author, and will be shared later. I will only share files that can be shared first.)

> 2d-ofdb-1k with patch aug. ->  pretrain_deit_tiny_patch16_224_2d-ofdb1k_patch__lr1.0e-3_epochs80000_bs256-last.pth
> 3d-ofdb-1k with patch aug. -> pretrain_deit_tiny_patch16_224_3d-ofdb1k_patch_lr1.0e-3_epochs80000_bs256-last.pth
> 3d-ofdb-1k with texture aug. -> pretrain_deit_tiny_patch16_224_3d-ofdb1k_texture_lr1.0e-3_epochs80000_bs256-last.pth
> 3d-ofdb-1k with patch and texture aug. -> pretrain_deit_tiny_patch16_224_3d-ofdb_patch_texture_lr1.0e-3_epochs80000_bs256-last.pth


In addition, I think the error in your code is probably due to a different version of timm and the names of the parameters have changed.

Below were the errors you encountered.
> omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model.optim.model_or_paramsfull_key:model.optim.model_or_params object_type=dict

I checked and it seems that the parameter of timm.optim.create_optimizer_v2 has been changed.
Details are as follows.
timm v0.4.12 -> [link](https://github.com/huggingface/pytorch-image-models/blob/7096b52a613eefb4f6d8107366611c8983478b19/timm/optim/optim_factory.py#L73)
timm v0.9.16 -> [link](https://github.com/huggingface/pytorch-image-models/blob/6e6f3686a7e06bcba37bbd3b7c755f04a516a1e7/timm/optim/optim_factory.py#L194C1-L195C6)
Therefore, it seems that the error can be resolved by deleting the model at the [link](https://github.com/ryoo-nakamura/OFDB/blob/main/main.py#L194) point.
